/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filmoteca;

import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author MEDAC
 */
public class Editar extends javax.swing.JDialog {

    public TableModelPeliculas table;
    private boolean ok;
    Pelicula edPelicula;
    JTable edJTable;

    /**
     * Constructor que recibe los parametros del JFrame -> Coleccion, e iguala
     * dos variables locales a los datos recibidos. Rellena los campos de texto
     * de este JFrame con los datos de la pelixula escogida y que queremos
     * actualizar.
     */
    public Editar(Pelicula p, Frame frame) {
        super(frame, true);
        ok = false;
        edPelicula = p;

        initComponents();

        tTitulo.setText(edPelicula.getTitulo());
        tAño.setText(String.valueOf(edPelicula.getAnyo()));
        tSinopsis.setText(edPelicula.getSinopsis());
        cbPuntuacion.setSelectedIndex(edPelicula.getPuntuacion() - 1);
        lID.setText(String.valueOf(edPelicula.getId()));

        try {
            ConexionDB4O.getInstance().conectar();

        } catch (Exception ex) {
            System.out.print(ex.getMessage());
        }
    }

    public Pelicula editarPeli() {
        this.setVisible(true);

        Pelicula pelicula = null;

        if (ok) {
            int id = Integer.parseInt(lID.getText());
            String titulo = tTitulo.getText();
            int anyo = Integer.parseInt(tAño.getText());
            int puntuacion = cbPuntuacion.getSelectedIndex() + 1;
            String sinopsis = tSinopsis.getText();

            pelicula = new Pelicula(id, titulo, anyo, puntuacion, sinopsis);
        }

        return pelicula;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tAño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbPuntuacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tSinopsis = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        lID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Titulo:");

        tTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTituloActionPerformed(evt);
            }
        });

        jLabel2.setText("Año:");

        tAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAñoActionPerformed(evt);
            }
        });

        jLabel3.setText("Punuacion:");

        cbPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        cbPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPuntuacionActionPerformed(evt);
            }
        });

        jLabel4.setText("Sinopsis:");

        tSinopsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSinopsisActionPerformed(evt);
            }
        });

        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actualizar.png"))); // NOI18N
        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/senal.png"))); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bActualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bCancelar))
                                    .addComponent(tSinopsis)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lID))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar)
                    .addComponent(bActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lID)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Botón actualizar que en primero lugar ejecuta un DELETE de la pelicula
     * escogida. Después ejecuta un INSERT con los nuevos datos de la pelicula a
     * introducir. En último lugar actualiza los datos del JTable con los nuevos
     * datos de la BBDD y cierra la ventana.
     */
    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        ok = true;
        dispose();
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAñoActionPerformed

    private void cbPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPuntuacionActionPerformed

    private void tTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTituloActionPerformed

    private void tSinopsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSinopsisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSinopsisActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cbPuntuacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lID;
    private javax.swing.JTextField tAño;
    private javax.swing.JTextField tSinopsis;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables
}
